version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: app-mysql
      working_dir: /application
      volumes:
        - ./mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=falcom@123
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=falcom@123
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: app-webserver
      working_dir: /application
      volumes:
          - ./app:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
        - mysql

    php-fpm:
      build: php
      container_name: app-php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - ./php/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
